default: &default
  adapter: postgresql
  encoding: unicode
  username: trantorcaaf
  password: Dfr368qE
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trantorcaaf_development

test:
  <<: *default
  database: trantorcaaf_test

production:
  <<: *default
  database: trantorcaaf_test
